search-biases:
  # `(?i)` means case insensitive
  - regex: (?i)browser
    convert-to: web browser
    boost-appids:
      - app.zen_browser.zen
      - io.github.ungoogled_software.ungoogled_chromium
      - org.chromium.Chromium
      - org.gnome.Epiphany
      - org.kde.falkon
      - org.mozilla.firefox
      - org.torproject.torbrowser-launcher

  - regex: (?i)vm
    convert-to: virtual machine
    boost-appids:
      - org.virt_manager.virt-manager
      - org.gnome.Boxes

  - regex: (?i)ide
    convert-to: development
    boost-appids:
      - org.gnome.Builder
      - org.kde.kdevelop

  - regex: (?i)yt
    convert-to: youtube
